export const USER_STATE_CHANGE = "USER_STATE_CHANGE"
export const USER_POST_STATE_CHANGE = "USER_POST_STATE_CHANGE"
export const POST_STATE_CHANGE = "POST_STATE_CHANGE"
export const GET_BOOKS = "GET_BOOKS"